on: 
  pull_request:
  push:
  workflow_dispatch:
jobs:
  runningTests:
    name: Running PHPunit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: graychen/phpunit-action@v1.0.0
