on: 
  pull_request:
  push:
  workflow_dispatch:
jobs:
  runningTests:
    name: Running PHPunit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: PHP Composer install
      uses: baschny/php-composer-action@v1
      with:
        args: --dev
